version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  reviewers:
  - chvp
  groups:
    babel:
      patterns:
        - "@babel*"
    mdi:
      patterns:
        - "@mdi/*"
    vue:
      patterns:
        - "@?vue*"
    eslint:
      patterns:
        - "eslint*"
  ignore:
    - dependency-name: "eslint-plugin-vuetify"
      update-types: ["version-update:semver-major"]
    - dependency-name: "eslint"
      update-types: ["version-update:semver-major"]
    - dependency-name: "@vue/eslint-config-prettier"
      update-types: ["version-update:semver-major"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  reviewers:
  - chvp
