version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
  groups:
    eslint:
      patterns:
        - "eslint*"
    mdi:
      patterns:
        - "@mdi/*"
    vite:
      patterns:
        - "@?vite*"
    vue:
      patterns:
        - "@?vue*"
  ignore:
    - dependency-name: "@types/node"
      update-types: ["version-update:semver-major"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
- package-ecosystem: nix
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
