name: Cachix

on:
  push:
    branches: [ main ]

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v13
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix build -L --no-link .#accentor-web
      - run: nix eval --json ".#accentor-web.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
  shell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v13
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix build -L --no-link .#devShells.$(nix eval --impure --expr "builtins.currentSystem").accentor-web
      - run: nix eval --json ".#devShells.$(nix eval --impure --expr 'builtins.currentSystem').accentor-web.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
