name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: accentor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build -L --no-link .#accentor-web
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint -- --no-fix --max-warnings 0 --format stylish
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npm run type-check
