name: Update

on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v15
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix flake update
      - run: nix build -L --no-link .#accentor-web
      - run: nix eval --json ".#accentor-web.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
  shell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v15
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix flake update
      - run: nix build -L --no-link .#devShells.$(nix eval --impure --expr "builtins.currentSystem").accentor-web
      - run: nix eval --json ".#devShells.$(nix eval --impure --expr 'builtins.currentSystem').accentor-web.outPath" | sed 's/"\(.*\)"/\1/' | cachix push accentor
  commit:
    runs-on: ubuntu-latest
    needs: [packages, shell]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: cachix/install-nix-action@V28
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v15
        with:
          name: accentor
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - run: nix flake update
      - uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "Update flake dependencies"
          commit_user_name:  Accentor Bot
          commit_user_email: accentor-bot@users.noreply.github.com
          commit_author: Accentor Bot <accentor-bot@users.noreply.github.com>
